"""Review round 3, comment 4: does concept evidence help where class names are weakly
grounded, outside painting?

Repeats the Oxford-IIIT Pet probe protocol (pets_arm.py: four backbones, five-template
prompt ensemble, pretrained logit scale, 20:80 class-stratified image-level resplit,
five seeds, identical grids, staged search with the ZLaP candidate, bAcc selection)
on three more domains chosen to span class-name grounding:

  dtd       Describable Textures, 47 classes, 5,640 images
  eurosat   EuroSAT RGB land cover, 10 classes, 27,000 images
  aircraft  FGVC-Aircraft variants, 100 classes, 10,000 images (bottom banner cropped)
  pets_s5   Oxford-IIIT Pet again, with a dictionary regenerated by Claude Sonnet 5 so
            that every probe dictionary comes from the same model as the style ones

Dictionaries are generated per class by headless Claude Sonnet 5 (the route of
r3_generate_dicts.py) with the Pet prompt structure and domain axes. Every prompt bans
the class name, direct synonyms and proper names; phrases containing a class-name stem
or a capitalised possessive are re-queried.

  --stage gen      assets/r3_dicts/probe_{domain}.json (+ raw attempts)
  --stage encode   analysis/r3_probe_cache/{domain}_{tag}.npz
  --stage eval     results/supplementary/round3/probe_per_seed.csv
"""
from __future__ import annotations

import argparse
import glob
import io
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

import numpy as np
import pandas as pd

import cef_paths
from scipy.special import softmax

import pets_arm as P
from cgpr_lab import HYPER_ROOT, metrics
from zlap_impl import precompute_knn, zlap_transductive

cef_paths.add_bundled_paths()

DATA = os.path.join(HYPER_ROOT, "data_probe")
CACHE = os.path.join(HYPER_ROOT, "analysis", "r3_probe_cache")
DICTS = os.path.join(HYPER_ROOT, "assets", "r3_dicts")
OUT = os.path.join(HYPER_ROOT, "results", "supplementary", "round3", "probe_per_seed.csv")
SPECS = P.SPECS
STOP = {"or", "and", "the", "of", "a", "an", "land", "type"}
POSSESSIVE = re.compile(r"\b([A-Z][\w.-]*(?:\s+(?:van|de|da|von|di)\s+[A-Z][\w.-]*)?"
                        r"(?:\s+[A-Z][\w.-]*)*)(?:'s|s'|’s|s’)")


def possessive(phrase):
    m = POSSESSIVE.search(phrase)
    return m.group(1) if m else None


EUROSAT_NAMES = ["Annual Crop", "Forest", "Herbaceous Vegetation", "Highway",
                 "Industrial Buildings", "Pasture", "Permanent Crop", "Residential Buildings",
                 "River", "SeaLake"]
EUROSAT_CLIP = {"Annual Crop": "annual crop land", "Forest": "forest",
                "Herbaceous Vegetation": "brushland or shrubland", "Highway": "highway or road",
                "Industrial Buildings": "industrial buildings or commercial buildings",
                "Pasture": "pasture land", "Permanent Crop": "permanent crop land",
                "Residential Buildings": "residential buildings or homes or apartments",
                "River": "river", "SeaLake": "lake or sea"}
EUROSAT_LLM = {"Annual Crop": "Annual Crop Land", "Herbaceous Vegetation": "Herbaceous Vegetation",
               "Pasture": "Pasture Land", "Permanent Crop": "Permanent Crop Land",
               "SeaLake": "Sea or Lake", "Highway": "Highway or Road"}

TEMPLATE = """Category: "{display_name}"

List 10 short visual phrases (3-6 words each) that describe how a viewer could visually recognize this category in {medium}, WITHOUT naming the category itself. Cover a mix of:
{axes}

Do not include the category name or a direct synonym of it in any phrase.{extra}
Output ONLY a JSON array of strings, nothing else."""

DOMAINS = {
    "dtd": dict(
        system="You are a computer vision expert helping build a visual concept dictionary "
               "for zero-shot texture classification.",
        medium="a photograph of a surface or texture",
        axes=["repeating element or local pattern", "surface relief and tactile quality",
              "regularity, orientation and scale", "colour and contrast",
              "materials or objects that typically show it"],
        extra="",
        templates=["a photo of a {} texture.", "a photo of a {} pattern.",
                   "a photo of a {} thing.", "a photo of a {} object.",
                   "a photo of the {} texture."]),
    "eurosat": dict(
        system="You are a remote sensing expert helping build a visual concept dictionary "
               "for zero-shot land-cover classification of satellite images.",
        medium="a low-resolution RGB satellite image patch",
        axes=["colour and tone", "texture and grain", "shapes and geometry of parcels, "
              "structures or water", "spatial layout and surroundings",
              "typical variation across seasons or regions"],
        extra="",
        templates=["a centered satellite photo of {}.", "a centered satellite photo of a {}.",
                   "a centered satellite photo of the {}.", "a satellite photo of {}.",
                   "an aerial photo of {}."]),
    "aircraft": dict(
        system="You are an aviation expert helping build a visual concept dictionary for "
               "zero-shot aircraft variant classification.",
        medium="a photograph of an aircraft",
        axes=["fuselage length and proportions", "number, type and placement of engines",
              "wing, winglet and tail configuration",
              "nose, cockpit windows, doors and landing gear",
              "features that distinguish it from closely related variants"],
        extra="\nDo not name the manufacturer, the model family, any airline or any person.",
        templates=["a photo of a {}, a type of aircraft.", "a photo of the {}, a type of aircraft.",
                   "a photo of a {} aircraft.", "a photo of the {} airplane.",
                   "a close-up photo of a {}, a type of aircraft."]),
    "pets_s5": dict(
        system="You are a zoology expert helping build a visual concept dictionary for "
               "zero-shot pet breed classification.",
        medium="a photograph",
        axes=["coat texture / fur length", "colour and markings", "head and muzzle shape",
              "ears and eyes", "body build and posture"],
        extra="",
        templates=P.TEMPLATES),
}


# ── inventories: (items, labels, classes, clip display, llm display) ─────────────
def inventory(domain):
    if domain == "dtd":
        paths = sorted(glob.glob(os.path.join(DATA, "dtd", "images", "*", "*.jpg")))
        names = [os.path.basename(os.path.dirname(p)) for p in paths]
        classes = sorted(set(names))
        return paths, np.array([classes.index(n) for n in names]), classes, \
            {c: c for c in classes}, {c: c.capitalize() for c in classes}
    if domain == "eurosat":
        import pyarrow.parquet as pq
        items, labels = [], []
        for split in ("train", "validation", "test"):
            t = pq.read_table(os.path.join(DATA, "eurosat", f"{split}.parquet")).to_pylist()
            items += [r["image"]["bytes"] for r in t]
            labels += [int(r["label"]) for r in t]
        return items, np.array(labels), EUROSAT_NAMES, EUROSAT_CLIP, \
            {c: EUROSAT_LLM.get(c, c) for c in EUROSAT_NAMES}
    if domain == "aircraft":
        root = os.path.join(DATA, "fgvc-aircraft-2013b", "data")
        classes = [l.strip() for l in open(os.path.join(root, "variants.txt")) if l.strip()]
        ids, var, manu = [], {}, {}
        for split in ("train", "val", "test"):
            for l in open(os.path.join(root, f"images_variant_{split}.txt")):
                i, v = l.strip().split(" ", 1)
                ids.append(i)
                var[i] = v
            for l in open(os.path.join(root, f"images_manufacturer_{split}.txt")):
                i, m = l.strip().split(" ", 1)
                manu[i] = m
        ids = sorted(ids)
        v2m = {}
        for i in ids:
            v2m.setdefault(var[i], {}).setdefault(manu[i], 0)
            v2m[var[i]][manu[i]] += 1
        llm = {v: f"{max(m, key=m.get)} {v}" for v, m in v2m.items()}
        paths = [os.path.join(root, "images", f"{i}.jpg") for i in ids]
        return paths, np.array([classes.index(var[i]) for i in ids]), classes, \
            {c: c for c in classes}, llm
    if domain == "pets_s5":
        paths, labels, classes = P.inventory()
        return paths, labels, classes, {c: P.display(c) for c in classes}, \
            {c: P.display(c) for c in classes}
    raise ValueError(domain)


# ── dictionary generation ────────────────────────────────────────────────────────
def leak_patterns(display):
    toks = [t for t in re.findall(r"[A-Za-z0-9]+", display.lower())
            if t not in STOP and (len(t) >= 4 or t.isdigit() or any(ch.isdigit() for ch in t))]
    pats = []
    for t in toks:
        stem = t if (len(t) < 6 or any(ch.isdigit() for ch in t)) else t[:max(4, len(t) - 2)]
        pats.append(re.compile(r"\b" + re.escape(stem) + r"\w*", re.I))
    return pats


def generate(domain, workers=8):
    import r3_generate_dicts as G
    cfg = DOMAINS[domain]
    _, _, classes, clip_names, llm_names = inventory(domain)
    rawdir = os.path.join(DICTS, "raw", f"probe_{domain}")
    os.makedirs(rawdir, exist_ok=True)
    tmpl = TEMPLATE.format(display_name="{display_name}", medium=cfg["medium"],
                           axes="\n".join(f"- {a}" for a in cfg["axes"]), extra=cfg["extra"])

    def one(c):
        f = os.path.join(rawdir, re.sub(r"[^A-Za-z0-9]+", "_", c) + ".json")
        if os.path.exists(f):
            return c, json.load(open(f))
        pats = leak_patterns(llm_names[c]) + leak_patterns(clip_names[c])
        attempts, phrases = [], None
        for _ in range(G.MAX_TRIES):
            d = G.call(cfg["system"], tmpl.format(display_name=llm_names[c]))
            e = dict(result=d.get("result"), modelUsage=d.get("modelUsage"))
            try:
                ph = G.parse(d["result"])
            except Exception as ex:  # noqa: BLE001
                e["rejected"] = f"unparseable {ex!r}"
                attempts.append(e)
                continue
            bad = {p: [pt.pattern for pt in pats if pt.search(p)] + ([f"possessive {possessive(p)}"]
                                                                     if possessive(p) else [])
                   for p in ph}
            bad = {p: v for p, v in bad.items() if v}
            e["violations"] = bad
            if bad or len(ph) < 8:
                e["rejected"] = "leak" if bad else f"{len(ph)} phrases"
                attempts.append(e)
                continue
            attempts.append(e)
            phrases = ph
            break
        if phrases is None:
            last = [a for a in attempts if "violations" in a][-1]
            phrases = [p for p in G.parse(last["result"]) if p not in last["violations"]]
            attempts.append({"fallback": "dropped violating phrases from the last answer"})
        rec = dict(cls=c, llm_display=llm_names[c], attempts=attempts, phrases=phrases,
                   n_attempts=len([a for a in attempts if "result" in a]))
        json.dump(rec, open(f, "w"), indent=1, ensure_ascii=False)
        return c, rec

    with ThreadPoolExecutor(workers) as ex:
        recs = dict(ex.map(one, classes))
    out = {"_meta": dict(domain=domain, model=G.MODEL, system_prompt=cfg["system"],
                         prompt_template=tmpl, route="headless Claude Code CLI, as r3_generate_dicts.py",
                         llm_display_names=llm_names,
                         attempts_per_class={c: recs[c]["n_attempts"] for c in classes},
                         fallbacks=[c for c in classes if any("fallback" in a for a in recs[c]["attempts"])])}
    for c in classes:
        out[c] = recs[c]["phrases"]
    json.dump(out, open(os.path.join(DICTS, f"probe_{domain}.json"), "w"), indent=1, ensure_ascii=False)
    print(f"[gen] {domain}: {sum(len(out[c]) for c in classes)} phrases, "
          f"{sum(recs[c]['n_attempts'] - 1 for c in classes)} re-queries, "
          f"fallbacks {out['_meta']['fallbacks']}", flush=True)


# ── encoding ─────────────────────────────────────────────────────────────────────
class _DS:
    def __init__(self, items, preprocess, crop_bottom):
        self.items, self.pre, self.crop = items, preprocess, crop_bottom

    def __len__(self):
        return len(self.items)

    def __getitem__(self, i):
        from PIL import Image
        it = self.items[i]
        im = Image.open(io.BytesIO(it) if isinstance(it, (bytes, bytearray)) else it).convert("RGB")
        if self.crop:
            im = im.crop((0, 0, im.width, im.height - self.crop))
        return self.pre(im)


def encode(domain):
    import torch
    from vlm_comparison import VLMEncoder
    os.makedirs(CACHE, exist_ok=True)
    items, labels, classes, clip_names, _ = inventory(domain)
    d = json.load(open(os.path.join(DICTS, f"probe_{domain}.json")))
    phrases, owners = [], []
    for ci, c in enumerate(classes):
        for p in d[c]:
            phrases.append(p)
            owners.append(ci)
    owners = np.array(owners)
    for tag, (mn, pt, _) in SPECS.items():
        f = os.path.join(CACHE, f"{domain}_{tag}.npz")
        if os.path.exists(f):
            continue
        enc = VLMEncoder(mn, pt, device=None)
        if domain == "pets_s5":
            old = np.load(os.path.join(P.CACHE, f"{tag}.npz"), allow_pickle=True)
            assert list(old["classes"]) == classes and (old["labels"] == labels).all()
            img = old["image_embs"]
        else:
            # threads, not DataLoader workers: the container's /dev/shm is too small
            ds_ = _DS(items, enc.preprocess, 20 if domain == "aircraft" else 0)
            feats = []
            with ThreadPoolExecutor(16) as pool, torch.no_grad():
                for s in range(0, len(ds_), 256):
                    x = torch.stack(list(pool.map(ds_.__getitem__, range(s, min(s + 256, len(ds_))))))
                    z = enc.model.encode_image(x.to(enc.device)).float()
                    feats.append((z / z.norm(dim=-1, keepdim=True)).cpu().numpy())
            img = np.concatenate(feats)
        txt = enc.get_text_embeddings([clip_names[c] for c in classes],
                                      templates=DOMAINS[domain]["templates"], display_names=None)
        scale = enc.model.logit_scale.exp().item() if hasattr(enc.model, "logit_scale") else 1.0
        Y = softmax((img @ txt.T) * scale, axis=1)
        cemb = {"full": enc.encode_texts(phrases),
                "dclip": enc.encode_texts([f"{clip_names[classes[o]]}, which has {p}"
                                           for p, o in zip(phrases, owners)])}
        for v in ["rand_chars", "rand_words"]:
            cemb[v] = enc.encode_texts(P.control_phrases(v, phrases))
        np.savez(f, image_embs=img, text_embs=txt, Y=Y, labels=labels,
                 classes=np.array(classes, dtype=object), owners=owners,
                 **{f"c_{k}": v for k, v in cemb.items()})
        print(f"[encode] {domain} {tag}: {img.shape}, vanilla top1 "
              f"{(Y.argmax(1) == labels).mean():.3f}", flush=True)
        del enc
        torch.cuda.empty_cache()


# ── evaluation: pets_arm.evaluate, generalised, plus selected w and per-class recall ──
def eval_domain(domain):
    rows = []
    for tag, (_, _, label) in SPECS.items():
        d = np.load(os.path.join(CACHE, f"{domain}_{tag}.npz"), allow_pickle=True)
        X, clf, Yv, labels = d["image_embs"], d["text_embs"], d["Y"], d["labels"]
        classes, owners = list(d["classes"]), d["owners"]
        C = len(classes)
        DD = {k: (d[f"c_{k}"], owners) for k in ["full", "dclip", "rand_chars", "rand_words"]}
        DD["shuffle_owner"] = (d["c_full"], owners[np.random.default_rng(0).permutation(len(owners))])
        COLS = {n: [np.where(o == c)[0] for c in range(C)] for n, (_, o) in DD.items()}
        for seed in P.SEEDS:
            vi, ti = P.split(labels, seed)
            mu = {n: (X[vi] @ DD[n][0].T).mean(0, keepdims=True) for n in DD}
            V = (X[vi], Yv[vi], labels[vi])
            T = (X[ti], Yv[ti], labels[ti])
            M = lambda s, l: metrics(s, l, classes)
            cache = {id(V): precompute_knn(V[0], clf, max(P.KS)),
                     id(T): precompute_knn(T[0], clf, max(P.KS))}
            cos_cache, memo = {}, {}

            def evidence(embs, tau, db, dn):
                Sm = embs @ DD[dn][0].T
                if db:
                    Sm = Sm - mu[dn]
                Sm = Sm / tau
                Sm -= Sm.max(1, keepdims=True)
                A = np.exp(Sm)
                A /= A.sum(1, keepdims=True)
                Yc = np.stack([A[:, cc].sum(1) for cc in COLS[dn]], 1)
                return Yc / (Yc.sum(1, keepdims=True) + 1e-12)

            def score(part, g, e, dn="full"):
                tau, w, db, base = e
                if id(part) not in cos_cache:
                    cos_cache[id(part)] = part[0] @ clf.T
                B = cos_cache[id(part)] if base == "cos" else part[1]
                if w == 0:
                    Yf = B
                else:
                    Yc = evidence(part[0], tau, db, dn)
                    if base == "cos":
                        Yc = Yc * B.max(axis=1, keepdims=True)
                    Yf = (1 - w) * B + w * Yc
                return zlap_transductive(part[0], clf, *g, cross_affinity=Yf, knn_cache=cache[id(part)])

            def vm(g, e, dn):
                key = (g, e if e[1] > 0 else (0, 0, 0, e[3]), dn if e[1] > 0 else "")
                if key not in memo:
                    memo[key] = M(score(V, g, e, dn), V[2])["bacc"]
                return memo[key]

            gz = max(P.GRAPH, key=lambda c: vm(c, P.ZL_E, "full"))

            def staged(dn="full", pool=P.EVID):
                g = max(P.GRAPH, key=lambda c: vm(c, P.INIT_EVID, dn))
                e = max(pool, key=lambda c: vm(g, c, dn))
                g = max(P.GRAPH, key=lambda c: vm(c, e, dn))
                return max([(g, e), (gz, P.ZL_E)], key=lambda ge: vm(ge[0], ge[1], dn))

            def emit(method, s, cfg="", w=np.nan):
                m = M(s, T[2])
                pred = s.argmax(1)
                rec = [float((pred[T[2] == c] == c).mean()) for c in range(C)]
                rows.append(dict(domain=domain, backbone=label, seed=seed, method=method,
                                 bacc=m["bacc"], top1=m["top1"], cfg=str(cfg), w=w,
                                 recall=json.dumps(rec)))

            emit("Vanilla", T[1])
            emit("ZLaP", score(T, gz, P.ZL_E), (gz, P.ZL_E), 0.0)
            g, e = staged()
            emit("CEF", score(T, g, e), (g, e), e[1])
            g0, e0 = staged(pool=[c for c in P.EVID if c[1] == 0])
            emit("CEF w=0", score(T, g0, e0), (g0, e0), 0.0)
            for dn in P.CTRL:
                gc, ec = staged(dn=dn)
                emit(f"CEF [{dn}]", score(T, gc, ec, dn), (gc, ec), ec[1])
            demb, downer = DD["dclip"]
            dcols = [np.where(downer == c)[0] for c in range(C)]
            mc = lambda Sx: np.stack([Sx[:, cc].mean(1) for cc in dcols], 1)
            proto = np.stack([demb[downer == c].mean(0) / (np.linalg.norm(demb[downer == c].mean(0)) + 1e-12)
                              for c in range(C)])
            for name, sv, st in (("DCLIP", mc(V[0] @ demb.T), mc(T[0] @ demb.T)),
                                 ("CuPL", V[0] @ proto.T, T[0] @ proto.T)):
                emit(name, st)
                av, at = np.clip(sv, 0, None), np.clip(st, 0, None)
                gd = max(P.GRAPH, key=lambda c: M(zlap_transductive(
                    V[0], clf, *c, cross_affinity=av, knn_cache=cache[id(V)]), V[2])["bacc"])
                emit(f"{name} + ZLaP", zlap_transductive(T[0], clf, *gd, cross_affinity=at,
                                                         knn_cache=cache[id(T)]), gd)
            print(f"  [{domain}/{label}] seed {seed} done", flush=True)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", choices=["gen", "encode", "eval"], required=True)
    ap.add_argument("--domains", nargs="+", default=list(DOMAINS))
    ap.add_argument("--workers", type=int, default=4)
    a = ap.parse_args()
    if a.stage == "gen":
        for dm in a.domains:
            generate(dm)
    elif a.stage == "encode":
        for dm in a.domains:
            encode(dm)
    else:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        from concurrent.futures import ProcessPoolExecutor
        with ProcessPoolExecutor(max_workers=a.workers) as ex:
            for rows in ex.map(eval_domain, a.domains):
                df = pd.DataFrame(rows)
                if os.path.exists(OUT):
                    df = pd.concat([pd.read_csv(OUT), df], ignore_index=True)
                df.drop_duplicates(subset=["domain", "backbone", "seed", "method"],
                                   keep="last").to_csv(OUT, index=False)
                print(f"[saved] {rows[0]['domain']}", flush=True)


if __name__ == "__main__":
    main()
