#!/usr/bin/env bash
# Reproduce every analysis added by the 2026-09-12 revision, in order.
#
# Do not edit this file while it is running: bash reads a script by byte
# offset, so rewriting it under a live shell wedges that shell. Write a new
# script instead.
#
# Stages 1 and 4a need the four VLM text/image encoders (GPU, model weights
# cached locally). Everything else runs on cached embeddings.
set -euo pipefail
cd "$(dirname "$0")"
PY="${PYTHON_BIN:-python3}"

echo "== 1. encode the control dictionaries (random / templated descriptors)"
$PY -u control_dicts.py

echo "== 2. descriptor baselines + dictionary controls, per seed"
$PY -u review_controls.py

echo "== 3. fixed-configuration transfer (needs stage 2's selections)"
$PY -u review_transfer.py

echo "== 4a. domain-transfer probe: encode Oxford-IIIT Pet"
$PY -u pets_arm.py --stage encode

echo "== 4b. domain-transfer probe: evaluate"
$PY -u pets_arm.py --stage eval

echo "== 5. paired significance tests"
$PY -u review_stats.py

echo "== 6. tables and prose macros"
$PY -u make_review_tables.py

echo "== 7. guard every directional claim in the manuscript"
$PY -u verify_review_claims.py

echo "== 8. rebuild the manuscript"
bash ../paper3/build.sh
echo "done"
